### ISSUE TITLE
Prioritize file downloads

### ISSUE THREAD

**Issue by xuset** [xuset/planktos#26]
Currently, each file is downloaded in the order it appears in the torrent. This can cause problems like large files being downloaded first before they're needed while the much needed index.html is the last file in the torrent and the last to be downloaded.

WebTorrent allows the priority of a given piece range to be changed such that pieces with a higher priority are downloaded before those with lower priority. So when a file is requested, a message should be sent to the web page that is downloading the torrent to instruct it to raise the priority of the requested file's pieces.

**Comment by georgeaf99** [comment]
I agree that this should be the default approach for loading files from a torrent. The alternative would be to only load specific files from the torrent; however, that degrades the health of the torrent overall, since seeders may only have popular parts of the torrent.

This method, in conjunction with distributing the website across multiple torrents, should do a good job in ensuring that every page in a website is available through Planktos. Using this approach we can now consider better optimal strategies for breaking up the website into multiple torrents. My thoughts for an ideal solution would be to consider the website as a graph, where pages are nodes and links between them are edges, and to split the graph into minimally connected subgraphs.
